#include "openscale/import.hpp"
#include "openscale/hardware.hpp"
#include "openscale/feasibility.hpp"
#include "openscale/runtime.hpp"
#include "openscale/modules.hpp"
#include "openscale/model.hpp"
#include "openscale/planner.hpp"
#include <iostream>
#include <iomanip>
using namespace openscale;
static void usage(){std::cout<<"OpenScale\n\nCommands:\n  hardware\n  modules\n  inspect <model.gguf|model.safetensors|model.av>\n  convert <input> <output.av>\n  verify <model.av>\n  benchmark <model.av> [iterations]\n  analyze <params> <RAM_GB> [bits] [context]\n  plan <model.av>\n  run <model.av> --prompt <text>\n\nNote: run is currently a runtime-planning/loader path, not a full transformer decoder.\n";}
static void show(const ModelInfo&i,const std::vector<TensorInfo>&t){std::cout<<"name: "<<i.name<<"\narchitecture: "<<i.architecture<<"\nparameters: "<<i.parameter_count<<"\nlayers: "<<i.layers<<"\nhidden: "<<i.hidden_size<<"\nheads: "<<i.attention_heads<<"\nkv_heads: "<<i.kv_heads<<"\ncontext: "<<i.context_length<<"\ntensors: "<<t.size()<<"\n";}
int main(int argc,char**argv){if(argc<2){usage();return 2;}std::string cmd=argv[1],e;if(cmd=="hardware"){std::cout<<hardware_string(detect_hardware())<<"\n";return 0;}if(cmd=="modules"){for(auto&m:list_modules())std::cout<<m.kind<<"\t"<<m.name<<"\t"<<m.status<<"\t"<<m.detail<<"\n";return 0;}if(cmd=="convert"){if(argc<4){usage();return 2;}if(!convert_model_to_av(argv[2],argv[3],e)){std::cerr<<"ERROR: "<<e<<"\n";return 1;}return 0;}if(cmd=="inspect"){if(argc<3){usage();return 2;}std::string p=argv[2];ModelInfo i;std::vector<TensorInfo>t;bool ok=false;if(p.ends_with(".av")){AvReader r;ok=r.open(p,e)&&r.verify(e);if(ok)show(r.info(),r.tensors());}else if(p.ends_with(".gguf")){ok=inspect_gguf(p,i,t,e);if(ok)show(i,t);}else if(p.ends_with(".safetensors")){ok=inspect_safetensors(p,i,t,e);if(ok)show(i,t);}else e="unsupported format";if(!ok){std::cerr<<"ERROR: "<<e<<"\n";return 1;}return 0;}if(cmd=="verify"){if(argc<3){usage();return 2;}AvReader r;if(!r.open(argv[2],e)||!r.verify(e)){std::cerr<<"ERROR: "<<e<<"\n";return 1;}std::cout<<"OpenScale AV verification: OK\n";return 0;}if(cmd=="benchmark"){if(argc<3){usage();return 2;}Runtime r;if(!r.load(argv[2],e)){std::cerr<<"ERROR: "<<e<<"\n";return 1;}RuntimeBenchmark b;if(!r.benchmark(argc>3?std::stoul(argv[3]):100,b,e)){std::cerr<<"ERROR: "<<e<<"\n";return 1;}std::cout<<std::fixed<<std::setprecision(3)<<"accounted bytes/s: "<<b.bytes_per_sec<<"\ncontainer benchmark seconds: "<<b.seconds<<"\nNOTE: not token/s; full decoder kernels are not enabled yet.\n";return 0;}if(cmd=="analyze"){if(argc<4){usage();return 2;}ModelInfo i;i.parameter_count=std::stoull(argv[2]);double ram=std::stod(argv[3]);double bits=argc>4?std::stod(argv[4]):4;uint64_t ctx=argc>5?std::stoull(argv[5]):4096;auto f=analyze(i,ram,bits,ctx);std::cout<<std::fixed<<std::setprecision(2)<<"weights: "<<(double)f.weight_gb<<" GB\nKV: "<<(double)f.kv_gb<<" GB\nworking: "<<(double)f.working_gb<<" GB\ntotal estimate: "<<(double)f.total_gb<<" GB\nresident: "<<(f.resident?"YES":"NO")<<"\nstreaming needed: "<<(f.streaming?"YES":"NO")<<"\n"<<f.note<<"\n";return 0;}if(cmd=="plan"||cmd=="run"){if(argc<3){usage();return 2;}Model m;if(!m.load(argv[2],e)){std::cerr<<"ERROR: "<<e<<"\n";return 1;}auto p=plan(m,enumerate_backends());std::cout<<"backend: "<<(p.backend==BackendKind::CPU?"CPU":"other")<<"\nthreads: "<<p.threads<<"\nmmap weights: "<<(p.mmap_weights?"yes":"no")<<"\npaged KV: "<<(p.paged_kv?"yes":"no")<<"\nplan: "<<p.summary<<"\n";if(cmd=="run")std::cout<<"Model loaded successfully. Full transformer decode backend is the next execution layer.\n";return 0;}usage();return 2;}
